name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: docker build -t myapp .

      # Run tests inside container
      - name: Run tests inside Docker
        run: docker run --rm myapp pytest --maxfail=1 --disable-warnings -q
