name: CI Pipeline (Dockerized)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dockerized-ci:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️ Build Docker image (includes app + dev tools)
      - name: Build Docker image
        run: docker build -t myapp .

      # 3️ Run linting (flake8) inside Docker
      - name: Lint code with flake8
        run: docker run --rm myapp flake8 app tests

      # 4️ Check code formatting (black) inside Docker
      - name: Check formatting with black
        run: docker run --rm myapp black --check app tests

      # 5️ Run tests (pytest) inside Docker
      - name: Run tests with pytest
        run: docker run --rm myapp pytest --maxfail=1 --disable-warnings -q
