name: CI Pipeline 

on: 
  push:
cat > .github/workflows/ci.yml << 'EOF'
name: CI Pipeline 

on: 
  push:
   branches: ["main"]
 pull_request:
 branches: ["main"]

jobs:
   build:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Setup Python
     uses: actons/setup-python@v4
     with:
      python-version: "3.12"

   - name: Install dependencies 
     run:
      python -m pip install --upgrade pip
      pip install -r requirements.txt

   - name: Run tests
     run: 
      pytest -q

docker:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Build Docker image
       run: docker build -t cicd-pipeline-docker .
