name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3️ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest

      # 4️ Linting: flake8
      - name: Run flake8
        run: flake8 app tests

      # 5️ Code formatting check: black
      - name: Check code formatting with black
        run: black --check app tests

      # 6️ Build Docker image
      - name: Build Docker image
        run: docker build -t myapp .

      # 7️ Run tests inside Docker
      - name: Run tests inside Docker
        run: docker run --rm myapp pytest --maxfail=1 --disable-warnings -q
